# Form implementation generated from reading ui file 'calccc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(410, 700))
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        MainWindow.setStyleSheet("background-color: rgb(181, 255, 172);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 371, 41))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lineEdit.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"font: 63 20pt \"MS Shell Dlg 2\";")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 60, 371, 41))
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"font: 63 20pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 110, 91, 51))
        self.pushButton.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 110, 91, 51))
        self.pushButton_2.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 110, 91, 51))
        self.pushButton_3.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 110, 91, 51))
        self.pushButton_4.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 170, 91, 41))
        self.pushButton_5.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 170, 91, 41))
        self.pushButton_6.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(210, 170, 91, 41))
        self.pushButton_7.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 170, 91, 41))
        self.pushButton_8.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 230, 91, 41))
        self.pushButton_9.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(310, 230, 91, 41))
        self.pushButton_10.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 230, 91, 41))
        self.pushButton_11.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(110, 230, 91, 41))
        self.pushButton_12.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 290, 91, 41))
        self.pushButton_13.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(310, 290, 91, 41))
        self.pushButton_14.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(210, 290, 91, 41))
        self.pushButton_15.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(110, 290, 91, 41))
        self.pushButton_16.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 350, 91, 91))
        self.pushButton_17.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(310, 350, 91, 91))
        self.pushButton_18.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(110, 350, 91, 91))
        self.pushButton_20.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(210, 350, 91, 91))
        self.pushButton_21.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 241, 241);\n"
"font: 63 18pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(5, 5, 255);")
        self.pushButton_21.setObjectName("pushButton_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(lambda x:self.bosh("c"))
        self.pushButton_2.clicked.connect(lambda x:self.bosh("()"))
        self.pushButton_3.clicked.connect(lambda x:self.bosh("%")) 
        self.pushButton_4.clicked.connect(self.ochir)     
        self.pushButton_5.clicked.connect(lambda x:self.bosh("7"))
        self.pushButton_6.clicked.connect(lambda x:self.bosh("/"))
        self.pushButton_7.clicked.connect(lambda x:self.bosh("9")) 
        self.pushButton_8.clicked.connect(lambda x:self.bosh("8"))
        self.pushButton_9.clicked.connect(lambda x:self.bosh("4")) 
        self.pushButton_10.clicked.connect(lambda x:self.bosh("X"))
        self.pushButton_11.clicked.connect(lambda x:self.bosh("6"))
        self.pushButton_12.clicked.connect(lambda x:self.bosh("5"))
        self.pushButton_13.clicked.connect(lambda x:self.bosh("1"))
        self.pushButton_14.clicked.connect(lambda x:self.bosh("-"))
        self.pushButton_15.clicked.connect(lambda x:self.bosh("3"))
        self.pushButton_16.clicked.connect(lambda x:self.bosh("2"))
        self.pushButton_17.clicked.connect(lambda x:self.bosh("+/-"))
        self.pushButton_18.clicked.connect(lambda x:self.bosh("+"))
        self.pushButton_20.clicked.connect(lambda x:self.bosh("0"))
        self.pushButton_21.clicked.connect(lambda x:self.bosh(","))
    def bosh(self, txt:str):
        if txt=="=":
            amal=self.lineEdit.text()
            ans=eval()
            self.lineEdit_2.setText(str(ans))
        elif txt=="c":
            self.lineEdit.clear()
        else:
            self.lineEdit.setText(self.lineEdit.text()+txt)
            
    def ochir(self):
            txt = self.lineEdit.text()
            self.lineEdit.setText(txt[:-1])
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "с"))
        self.pushButton_2.setText(_translate("MainWindow", "()"))
        self.pushButton_3.setText(_translate("MainWindow", "%"))
        self.pushButton_4.setText(_translate("MainWindow", "<<<"))
        self.pushButton_5.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "/"))
        self.pushButton_7.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "X"))
        self.pushButton_11.setText(_translate("MainWindow", "6"))
        self.pushButton_12.setText(_translate("MainWindow", "5"))
        self.pushButton_13.setText(_translate("MainWindow", "1"))
        self.pushButton_14.setText(_translate("MainWindow", "-"))
        self.pushButton_15.setText(_translate("MainWindow", "3"))
        self.pushButton_16.setText(_translate("MainWindow", "2"))
        self.pushButton_17.setText(_translate("MainWindow", "+/-"))
        self.pushButton_18.setText(_translate("MainWindow", "+"))
        self.pushButton_20.setText(_translate("MainWindow", "0"))
        self.pushButton_21.setText(_translate("MainWindow", ","))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
